name: song_lyrics_app
description: A beautiful collection of spiritual songs for worship and praise.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^15.2.4
  
  # State Management & Storage
  shared_preferences: ^2.3.2
  
  # UI & Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.3.7

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/collection_covers/
    - assets/data/
    
  # Fonts (optional - for custom font families)
fonts:
    - family: Roboto
      fonts:
        - assets: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
        - assets: fonts/Roboto-VariableFont_wdth,wght.ttf
          weight: 700
    # Add more font families as needed